# All histograms and their configurations should be provided in this config

# Draw options for the ROOT classes
draw_options:
  TH1F: "hist"
  TH2F: "colz"
  TProfile: "hist"
  THStack: "hist"

# Max run size that an ERA can have for each group
max_era_run_size: 3

# Please provide all the histograms here
groups:
  - group_name: "JetMET"
    eos_directory: "JetMET1"
    tdirectory: "DQMData/Run {run_num_int}/JetMET/Run summary"
    description: ""
    plots:
      - name: "Jet/Cleanedak4PFJetsCHS/CHFrac_highPt_Barrel"
        dqm_link: "https://cmsweb.cern.ch/dqm/offline/start?runnr={run_num_int};dataset={dataset};sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=JetMet;size=M;root=JetMET/Jet/Cleanedak4PFJetsCHS;focus=JetMET/Jet/Cleanedak4PFJetsCHS/CHFrac_highPt_Barrel;zoom=yes;"
        type: "TH1F"
      - name: "Jet/Cleanedak4PFJetsCHS/ZJets/MPF_highPt_J_Barrel"
        dqm_link: "https://cmsweb.cern.ch/dqm/offline/start?runnr={run_num_int};dataset={dataset};sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=JetMet;size=M;root=JetMET/Jet/Cleanedak4PFJetsCHS/ZJets;focus=JetMET/Jet/Cleanedak4PFJetsCHS/ZJets/MPF_highPt_J_Barrel;zoom=yes;"
        type: "TH1F"
      - name: "MET/pfMETT1/Cleaned/METSig"
        dqm_link: "https://cmsweb.cern.ch/dqm/offline/start?runnr={run_num_int};dataset={dataset};sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=JetMet;size=M;root=JetMET/MET/pfMETT1/Cleaned;focus=JetMET/MET/pfMETT1/Cleaned/METSig;zoom=yes;"
        type: "TH1F"
      - name: "Jet/Cleanedak4PFJetsCHS/JetEnergyCorrVSEta"
        dqm_link: "https://cmsweb.cern.ch/dqm/offline/start?runnr={run_num_int};dataset={dataset};sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=JetMet;size=M;root=JetMET/Jet/Cleanedak4PFJetsCHS;focus=JetMET/Jet/Cleanedak4PFJetsCHS/JetEnergyCorrVSEta;zoom=yes;"
        type: "TProfile"
      - name: "Jet/Cleanedak4PFJetsCHS/PhiVSEta"
        dqm_link: "https://cmsweb.cern.ch/dqm/offline/start?runnr={run_num_int};dataset={dataset};sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=JetMet;size=M;root=JetMET/Jet/Cleanedak4PFJetsCHS;focus=JetMET/Jet/Cleanedak4PFJetsCHS/PhiVSEta;zoom=yes;"
        type: "TH2F"
  - group_name: "Muon"
    eos_directory: "Muon1"
    tdirectory: "DQMData/Run {run_num_int}/Muons/Run summary"
    description: ""
    plots:
      - name: "Tracking/innerTrack/GeneralProperties/NumberOfMeanRecHitsPerTrack_inner"
        dqm_link: "https://cmsweb.cern.ch/dqm/offline/start?runnr={run_num_int};dataset={dataset};sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=Muons;size=M;root=Muons/Tracking/innerTrack/GeneralProperties;focus=Muons/Tracking/innerTrack/GeneralProperties/NumberOfMeanRecHitsPerTrack_inner;zoom=yes;"
        type: "TH1F"
      - name: "globalMuons/GeneralProperties/Chi2Prob_glb"
        dqm_link: ""
        type: "TH1F"
      - name: "MuonRecoAnalyzer/GlbMuon_Glb_phiVSeta"
        dqm_link: ""
        type: "TH2F"
      - name: "diMuonHistograms/test"
        dqm_link: ""
        type: "TH1F"
  - group_name: "EGamma"
    eos_directory: "EGamma1"
    tdirectory: "DQMData/Run {run_num_int}/Egamma/Run summary"
    description: ""
    plots:
      - name: "gedPhotonAnalyzer/GoodCandidatePhotons/Et above 20 GeV/h_13_phoSigmaIetaIetaAllEcal"
        dqm_link: ""
        type: "TH1F"
      - name: "gedPhotonAnalyzer/GoodCandidatePhotons/Et above 20 GeV/h_18_e2x5VsEta"
        dqm_link: ""
        type: "TProfile"
      - name: "gedPhotonAnalyzer/GoodCandidatePhotons/Et above 20 GeV/h_38_ecalSumEBarrel"
        dqm_link: ""
        type: "TH1F"
      - name: "gedPhotonAnalyzer/GoodCandidatePhotons/Et above 20 GeV/h_47_hOverEAllEcal"
        dqm_link: ""
        type: "TH1F"
      - name: "gedPhotonAnalyzer/GoodCandidatePhotons/Et above 20 GeV/h_54_chHadIsoBarrel"
        dqm_link: ""
        type: "TH1F"
      - name: "gedPhotonAnalyzer/AllPhotons/Et above 20 GeV/h_13_phoSigmaIetaIetaAllEcal"
        dqm_link: ""
        type: "TH1F"
      - name: "gedPhotonAnalyzer/AllPhotons/Et above 20 GeV/h_18_e2x5VsEta"
        dqm_link: ""
        type: "TProfile"
      - name: "gedPhotonAnalyzer/AllPhotons/Et above 20 GeV/h_38_ecalSumEBarrel"
        dqm_link: ""
        type: "TH1F"
      - name: "gedPhotonAnalyzer/AllPhotons/Et above 20 GeV/h_47_hOverEAllEcal"
        dqm_link: ""
        type: "TH1F"
      - name: "gedPhotonAnalyzer/AllPhotons/Et above 20 GeV/h_54_chHadIsoBarrel"
        dqm_link: ""
        type: "TH1F"
      - name: "Electrons/Ele5_TagAndProbe/ele3_vertexEtaVsPhi"
        dqm_link: ""
        type: "TH2F"
      - name: "Electrons/Ele5_TagAndProbe/ele10_Eop_barrel"
        dqm_link: ""
        type: "TH1F"
      - name: "Electrons/Ele5_TagAndProbe/ele18_dPhiSc_propVtx_barrel"
        dqm_link: ""
        type: "TH1F"
      - name: "Electrons/Ele5_TagAndProbe/ele100_ptEff"
        dqm_link: ""
        type: "TH1F"
      - name: "Electrons/Ele5_TagAndProbe/ele201_mee_os"
        dqm_link: ""
        type: "TH1F"
