# Please provide all the histograms here
- group_name: "JetMET"
  eos_directory: "JetMET1"
  tdirectory: "DQMData/Run {run_num_int}/JetMET/Run summary"
  description: ""
  plots:
    - name: "Jet/Cleanedak4PFJetsCHS/CHFrac_highPt_Barrel"
      dqm_link: "https://cmsweb.cern.ch/dqm/offline/start?runnr={run_num_int};dataset={dataset};sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=JetMet;size=M;root=JetMET/Jet/Cleanedak4PFJetsCHS;focus=JetMET/Jet/Cleanedak4PFJetsCHS/CHFrac_highPt_Barrel;zoom=yes;"
      draw_opt: "hist"
      type: "TH1F"
    - name: "Jet/Cleanedak4PFJetsCHS/JetEnergyCorrVSEta"
      dqm_link: "https://cmsweb.cern.ch/dqm/offline/start?runnr={run_num_int};dataset={dataset};sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=JetMet;size=M;root=JetMET/Jet/Cleanedak4PFJetsCHS;focus=JetMET/Jet/Cleanedak4PFJetsCHS/JetEnergyCorrVSEta;zoom=yes;"
      draw_opt: "hist"
      type: "TProfile"
    - name: "Jet/Cleanedak4PFJetsCHS/PhiVSEta"
      dqm_link: "https://cmsweb.cern.ch/dqm/offline/start?runnr={run_num_int};dataset={dataset};sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=JetMet;size=M;root=JetMET/Jet/Cleanedak4PFJetsCHS;focus=JetMET/Jet/Cleanedak4PFJetsCHS/PhiVSEta;zoom=yes;"
      draw_opt: "colz"
      type: "TH2F"
    - name: "Jet/Cleanedak4PFJetsCHS/ZJets/MPF_highPt_J_Barrel"
      dqm_link: "https://cmsweb.cern.ch/dqm/offline/start?runnr={run_num_int};dataset={dataset};sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=JetMet;size=M;root=JetMET/Jet/Cleanedak4PFJetsCHS/ZJets;focus=JetMET/Jet/Cleanedak4PFJetsCHS/ZJets/MPF_highPt_J_Barrel;zoom=yes;"
      draw_opt: "hist"
      type: "TH1F"
    - name: "MET/pfMETT1/Cleaned/METSig"
      dqm_link: "https://cmsweb.cern.ch/dqm/offline/start?runnr={run_num_int};dataset={dataset};sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=JetMet;size=M;root=JetMET/MET/pfMETT1/Cleaned;focus=JetMET/MET/pfMETT1/Cleaned/METSig;zoom=yes;"
      draw_opt: "hist"
      type: "TH1F"
- group_name: "HLT"
  eos_directory: "HLTPhysics"
  tdirectory: "DQMData/Run {run_num_int}/HLT/Run summary"
  description: ""
  plots:
    - name: "JME/Jets/AK4/PF/HLT_PFJet260/effic_pfjeteta"
      dqm_link: "https://cmsweb.cern.ch/dqm/offline/start?runnr={run_num_int};dataset={dataset};sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=HLT;size=M;root=HLT/JME/Jets/AK4/PF/HLT_PFJet260;focus=HLT/JME/Jets/AK4/PF/HLT_PFJet260/effic_pfjeteta;zoom=yes;"
      draw_opt: "hist"
      type: "TH1F"
    - name: "JME/Jets/AK4/PF/HLT_PFJet260/effic_pfjeteta_HB"
      dqm_link: "https://cmsweb.cern.ch/dqm/offline/start?runnr={run_num_int};dataset={dataset};sampletype=offline_data;filter=all;referencepos=overlay;referenceshow=customise;referencenorm=True;referenceobj1=refobj;referenceobj2=none;referenceobj3=none;referenceobj4=none;search=;striptype=object;stripruns=;stripaxis=run;stripomit=none;workspace=HLT;size=M;root=HLT/JME/Jets/AK4/PF/HLT_PFJet260;focus=HLT/JME/Jets/AK4/PF/HLT_PFJet260/effic_pfjeteta_HB;zoom=yes;"
      draw_opt: "hist"
      type: "TH1F"
