# Server configs, check run.sh
# backend: cmsweb.cern.ch/dqm/mini_back/api/v1
# Auth proxy: `https://cmsweb.cern.ch/dqm/mini_back` <> `minidqm.dbs.svc.cluster.local:8081`
host: '0.0.0.0'
port: 8081
base_url: '/api/v1'
api_v1_prefix: '/api/v1'
environment: 'prod'
loglevel: 'warning'
allowed_cors_origins:
  - 'http://_MY_NODE_NAME_'
  - '*'

# Required to find DQM EOS metadata: runs, datasets, histogram root files
dqm_meta_store:
  base_dqm_eos_dir: '/eos/cms/store/group/comm_dqm/DQMGUI_data'
  find_tmp_results_file: '/data/TMP_DMQ_ROOT_FILES.txt'
  meta_store_json_file: '/data/DQM_META.json'
  last_n_run_years: 2
  file_suffix_pat: '*DQMIO.root'
  cache_retention_secs: 600
