host: '0.0.0.0'
port: 8081
base_url: '/ppdgui/api/v1'
api_v1_prefix: '/ppdgui/api/v1'
environment: 'prod'
loglevel: 'debug'
allowed_cors_origins:
  - 'http://_MY_NODE_NAME_'
  - 'http://_MY_NODE_NAME_:32000'
  - 'http://localhost'
  - 'http://localhost:80'
  - 'http://localhost:8080'
  - 'http://localhost:5173'
dqm_meta_store:
  base_dqm_eos_dir: '/eos/cms/store/group/comm_dqm/DQMGUI_data'
  find_tmp_results_file: '/data/dqm_root_files.txt'
  meta_store_json_file: '/data/dqm_meta.json'
  last_n_run_years: 2
  file_suffix_pat: '*DQMIO.root'
detector_histogram_groups:
  - gname: 'L1T'
    group_directory: 'JetMET1'
    histograms_tdirectory_pattern: 'DQMData/Run {run_num_int}/L1T/Run summary/L1TObjects/L1TJet/timing'
    description: 'Black&White, learn how to draw colorful'
    histograms:
      - name: 'jet_eta_phi_bx_0'
        type: 'TH2F'
      - name: 'jet_eta_phi_bx_minus1'
        type: 'TH2F'
      - name: 'jet_eta_phi_bx_minus2'
        type: 'TH2F'
      - name: 'jet_eta_phi_bx_plus1'
        type: 'TH2F'
      - name: 'jet_eta_phi_bx_plus2'
        type: 'TH2F'
  - group: 'HLT'
    group_directory: 'HLTPhysics'
    histograms_tdirectory_pattern: 'DQMData/Run {run_num_int}/HLT/Run summary/JME/Jets/AK4/PF/HLT_PFJet260'
    description: 'Axis scale is not correct, learn how to do draw it correctly'
    histograms:
      - name: 'effic_pfjeteta'
        type: 'TH1F'
      - name: 'effic_pfjeteta_HB'
        type: 'TH1F'
