kind: Service
apiVersion: v1
metadata:
  name: ppd-dashboard
spec:
  selector:
    app: ppd-dashboard
  type: NodePort
  ports:
    - name: backend
      port: 8081
      targetPort: 8081
      nodePort: 32001
      protocol: TCP
    - name: frontend
      port: 80
      targetPort: 80
      nodePort: 32000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppd-dashboard
  labels:
    app: ppd-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ppd-dashboard
  template:
    metadata:
      labels:
        app: ppd-dashboard
    spec:
      hostname: ppd-dashboard
      containers:
        # ------------- BACKEND ------------------------------------------------------
        - name: backend
          imagePullPolicy: Always
          image: mrceyhun/ppd-dashboard-back:latest
          command: [ "backend/run.sh" ]
          args: [ "/etc/secrets/keytab" ]
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_ENV
              value: "prod"
            - name: FAST_API_CONF
              value: "/data/backend/config"
          ports:
            - containerPort: 8081
              name: backend
          resources:
            limits:
              cpu: 2000m
              memory: 6Gi
            requests:
              cpu: 500m
              memory: 750Mi
          stdin: true
          tty: true
          volumeMounts:
            - name: ppd-dashboard-secrets
              mountPath: /etc/secrets
              readOnly: true
            - name: eos
              mountPath: /eos
              mountPropagation: HostToContainer
        # ------------- FRONTEND -----------------------------------------------------
        - name: frontend
          imagePullPolicy: Always
          image: mrceyhun/ppd-dashboard-front:latest
          command: [ "/run.sh" ]
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_ENV
              value: "prod"
            - name: VITE_BACKEND_API_BASE_URL # see frontend/src/main.js and frontend/run.sh, used in axios
              value: "http://$(MY_NODE_NAME):32001/ppd-dashboard/api"
          ports:
            - containerPort: 80
              name: frontend
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 750Mi
      volumes:
        - name: ppd-dashboard-secrets
          secret:
            secretName: ppd-dashboard-secrets
        - name: eos
          hostPath:
            path: /var/eos
