kind: Service
apiVersion: v1
metadata:
  name: ppdgui
spec:
  selector:
    app: ppdgui
  type: NodePort
  ports:
    - name: backend
      port: 8081
      targetPort: 8081
      nodePort: 32001
      protocol: TCP
    - name: frontend
      port: 80
      targetPort: 80
      nodePort: 32000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppdgui
  labels:
    app: ppdgui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ppdgui
  template:
    metadata:
      labels:
        app: ppdgui
    spec:
      hostname: ppdgui
      containers:
        # ------------- BACKEND ------------------------------------------------------
        - name: backend
          imagePullPolicy: Always
          image: mrceyhun/ppdgui-back:0.0.3
          command: [ "backend/run.sh" ]
          args: [ "/etc/secrets/keytab" ]
          env:
            - name: K8S_ENV
              value: "prod"
            - name: FAST_API_CONF
              value: "/data/backend/config.yaml"
          ports:
            - containerPort: 8081
              name: backend
          resources:
            limits:
              cpu: 2000m
              memory: 6Gi
            requests:
              cpu: 500m
              memory: 750Mi
          stdin: true
          tty: true
          volumeMounts:
            - name: ppdgui-secrets
              mountPath: /etc/secrets
              readOnly: true
            - name: eos
              mountPath: /eos
              mountPropagation: HostToContainer
        # ------------- FRONTEND -----------------------------------------------------
        - name: frontend
          imagePullPolicy: Always
          image: mrceyhun/ppdgui-front:0.0.3
          command: [ "/run.sh" ]
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_ENV
              value: "prod"
            - name: VITE_BACKEND_API_BASE_URL # see frontend/src/main.js and frontend/run.sh, used in axios
              value: "http://$(MY_NODE_NAME):32001/ppdgui/api"
          ports:
            - containerPort: 80
              name: frontend
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 750Mi
      volumes:
        - name: ppdgui-secrets
          secret:
            secretName: ppdgui-secrets
        - name: eos
          hostPath:
            path: /var/eos
